### ISSUE TITLE
Grammar load fails

### ISSUE THREAD

**Issue by frodrigo** [rezemika/oh_sanitizer#2]
Using Pyhton 3.4

```
(venv3)fred@osm110:/home/fred/oh_sanitizer$ python oh_sanitizer.py 
Traceback (most recent call last):
  File "oh_sanitizer.py", line 49, in <module>
    _PARSER = _get_parser()
  File "oh_sanitizer.py", line 46, in _get_parser
    return _lark.Lark(grammar, start="time_domain", parser="earley")
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/lark.py", line 160, in __init__
    tokens, self.rules, self.ignore_tokens = self.grammar.compile()
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/load_grammar.py", line 484, in compile
    expansions = rule_tree_to_text.transform(tree)
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/visitors.py", line 48, in transform
    return self._transform_tree(tree)
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/visitors.py", line 44, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/visitors.py", line 39, in _transform_children
    yield self._transform_tree(c) if isinstance(c, Tree) else c
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/visitors.py", line 45, in _transform_tree
    return self._call_userfunc(tree.data, children, tree.meta)
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/visitors.py", line 34, in _call_userfunc
    return f(children)
  File "/home/fred/frodrigo-osmose-backend/venv3/lib/python3.4/site-packages/lark/load_grammar.py", line 250, in alias
    assert _alias is None, (alias, expansion, '-', _alias)  # Double alias not allowed
AssertionError: (Token(RULE, 'monthday_date_easter'), ([NonTerminal('year'), Terminal('__IGNORE_0'), Terminal('EASTER'), NonTerminal('day_offset')], None), '-', ([NonTerminal('year'), Terminal('__IGNORE_0'), Terminal('EASTER')], None))

```

**Comment by rezemika** [comment]
Y'our right. I just checked, the last `lark-parser` release contains breaking changes. You need the `0.5.6` version. I'll try to fix this soon.

**Comment by frodrigo** [comment]
Parsing of all kind of countries is now ok for me.
Can you fix this, or setup the right dependency version of lark-parser, please?

**Comment by rezemika** [comment]
I just released a version 0.1.7 which add compatibility with the last version of `lark-parser` (v0.6.0 and higher). ;)

Related: lark-parser/lark#197

**Comment by frodrigo** [comment]
Thank you. It's fully OK right now.

Note, on osmose I report only `InconsistentField` exception as I can't distinguish required fix or not.

**Comment by hwinning** [comment]
Similar issue but different cause: `Dynamic Earley doesn't support weights on terminals`. The other two lark-parser algorithms also failed to load the grammar but for different reasons.

This is using `lark-parser==0.7.1` and `oh_sanitizer==0.1.10` on `python37` (on windows). Should I create a new issue for this?

**Comment by frodrigo** [comment]
We are sticky on old version because last version removed this feature.

**Comment by frodrigo** [comment]
Note, we have a improved version here: https://github.com/osm-fr/osmose-backend/tree/master/modules/oh_sanitizer

**Comment by rezemika** [comment]
Sorry for the lack of maintenance, I didn't see this breaking update on Lark. Unfortunately, I don't have much free time, so I suggest you to use the frodrigo's version, if you're hurry and really want something reliable.
