### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by frodrigo** [rezemika/oh_sanitizer#4]
```
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from oh_sanitizer import sanitize_field
>>> print(sanitize_field("Mo-Su 08:00-18:00; Apr 10-15 off; Jun 08:00-14:00; Aug off; Dec 25 off"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/oh_sanitizer/main.py", line 297, in sanitize_field
    new_field = SanitizerTransformer().transform(tree)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/lark/tree.py", line 121, in transform
    return f(items)
  File "/home/fred/frodrigo-osmose-backend/venv/local/lib/python2.7/site-packages/oh_sanitizer/main.py", line 81, in monthday_date_day_to_day
    monthday_to = int(args[2].value)
IndexError: list index out of range
```

**Comment by rezemika** [comment]
Fixed in the new `0.1.3` version. Thank you for your feedbacks!
