### ISSUE TITLE
Non-ASCII character '\xc3'

### ISSUE THREAD

**Issue by frodrigo** [rezemika/oh_sanitizer#9]
On release 1.5 with pyhton 2.7

```
(venv)fred@osm110:/home/fred/frodrigo-osmose-backend$ pip install --upgrade oh_sanitizer
Downloading/unpacking oh-sanitizer from https://files.pythonhosted.org/packages/d9/2c/01fc4bbaa733ced0022d555d7b54baab86ef27b78f81378deace44bcc4a3/oh_sanitizer-0.1.5.tar.gz#sha256=cc314c244af4ba2895b93a0e4c91555b1c7cbdf16e55645233b6b565deb91a18
  Downloading oh_sanitizer-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip-build-r6M3mz/oh-sanitizer/setup.py) egg_info for package oh-sanitizer
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-r6M3mz/oh-sanitizer/setup.py", line 4, in <module>
        import oh_sanitizer
      File "oh_sanitizer/__init__.py", line 26, in <module>
        from oh_sanitizer.main import sanitize_field, SanitizeError, InconsistentField
      File "oh_sanitizer/main.py", line 152
    SyntaxError: Non-ASCII character '\xc3' in file oh_sanitizer/main.py on line 152, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by rezemika** [comment]
Just released a v0.1.6 which fixes this (and a UnicodeWarning in string comparison).
